spring:
  application:
    name: PowerLog

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/power_log?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  sql:
    init:
      mode: never

logging:
  level:
    org: WARN
    blog: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

security:
  jwt:
    secret-key: ${SECRET_KEY}
    expiration-time: ${EXPIRATION_TIME}

#upload:
#  path: