spring:
  application:
    name: PowerLog

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/power_log?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  sql:
    init:
      mode: never

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Disable Kafka auto-configuration
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

logging:
  level:
    org: WARN
    blog: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

security:
  jwt:
    secretKey: ${SECRET_KEY}
    accessTokenExpiration: ${ACCESS_TOKEN_EXPIRATION}
    refreshTokenExpiration: ${REFRESH_TOKEN_EXPIRATION}
    rememberMeRefreshTokenExpiration: ${REMEMBER_ME_REFRESH_TOKEN_EXPIRATION}
    accessTokenCookieMaxAge: ${ACCESS_TOKEN_COOKIE_MAX_AGE}
    refreshTokenCookieMaxAge: ${REFRESH_TOKEN_COOKIE_MAX_AGE}
    rememberMeRefreshTokenCookieMaxAge: ${REMEMBER_ME_REFRESH_TOKEN_COOKIE_MAX_AGE}

server:
  error:
    whitelabel:
      enabled: false
    path: /error

admin:
  email: ${ADMIN_EMAIL}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}